# Generated by Django 3.2.6 on 2021-08-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0006_auto_20210819_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='author',
        ),
    ]
